// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxgD6s8GaOYbOOMnjmxukcIfGvUpPnJ9M',
    appId: '1:1081659507117:web:4125f2b084114c74482124',
    messagingSenderId: '1081659507117',
    projectId: 'consignment-40c50',
    authDomain: 'consignment-40c50.firebaseapp.com',
    storageBucket: 'consignment-40c50.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKVVz35tla-sufXFoB1nr7I-jMNO6AFRU',
    appId: '1:1081659507117:android:e40201e1c564dd6c482124',
    messagingSenderId: '1081659507117',
    projectId: 'consignment-40c50',
    storageBucket: 'consignment-40c50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUIOZWomV8qSbS_sDmMua9732n1-3AplA',
    appId: '1:1081659507117:ios:1fcca8a7bcbae319482124',
    messagingSenderId: '1081659507117',
    projectId: 'consignment-40c50',
    storageBucket: 'consignment-40c50.appspot.com',
    iosBundleId: 'com.example.flutterConsignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUIOZWomV8qSbS_sDmMua9732n1-3AplA',
    appId: '1:1081659507117:ios:dcb6a49aba9a7269482124',
    messagingSenderId: '1081659507117',
    projectId: 'consignment-40c50',
    storageBucket: 'consignment-40c50.appspot.com',
    iosBundleId: 'com.example.flutterConsignment.RunnerTests',
  );
}
